# Generated by Django 2.0.5 on 2018-07-31 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('game_type', models.CharField(max_length=150, verbose_name='type de jeu')),
                ('game_logo', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='logo jeu')),
                ('description', models.TextField(max_length=150)),
            ],
            options={
                'verbose_name': 'Jeu',
                'verbose_name_plural': 'Jeux',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('pseudo', models.CharField(max_length=100, unique=True, verbose_name='pseudo')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('firstname', models.CharField(max_length=50, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Joueur',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Opération Promotionnelle',
                'verbose_name_plural': 'Opérations Promotionnelles',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('value', models.IntegerField(verbose_name='valeur')),
            ],
            options={
                'verbose_name': 'Gain',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 7, 31, 13, 7, 48, 570720, tzinfo=utc))),
                ('result', models.CharField(max_length=150)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
            ],
            options={
                'verbose_name': 'Partie',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='games.Player')),
            ],
            options={
                'verbose_name': 'Gestionnaire',
            },
            bases=('games.player',),
        ),
        migrations.AddField(
            model_name='session',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Player'),
        ),
        migrations.AddField(
            model_name='session',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Reward'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Administrator'),
        ),
    ]
