# Generated by Django 2.0.5 on 2018-07-26 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='game_logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='logo jeu'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 15, 13, 38, 720472, tzinfo=utc)),
        ),
    ]
