# Generated by Django 2.0.5 on 2018-07-26 13:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='games',
            name='game_logo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 13, 37, 27, 240198, tzinfo=utc)),
        ),
    ]
