# Generated by Django 2.0.5 on 2018-07-25 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Gestionnaire',
            },
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Jeux'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Joueur'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Gain'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session'},
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 25, 7, 23, 35, 427233, tzinfo=utc)),
        ),
    ]
