# Generated by Django 2.0.5 on 2018-07-31 12:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Promotion')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Reward')),
            ],
            options={
                'verbose_name': 'Opération Promotionnelle Jeu(x) Gain(s)',
                'verbose_name_plural': 'Opérations Promotionnelles Jeu(x) Gain(s)',
            },
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 31, 12, 55, 1, 687971, tzinfo=utc)),
        ),
    ]
