# Generated by Django 2.0.5 on 2018-08-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180730_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Promotion')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Reward')),
            ],
            options={
                'verbose_name': 'Opération Promotionnelle Jeu(x) Gain(s)',
                'verbose_name_plural': 'Opérations Promotionnelles Jeu(x) Gain(s)',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='dateNaissance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='img_player',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='pseudo',
            field=models.CharField(max_length=40, verbose_name='mot de passe'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='reward',
            field=models.ManyToManyField(through='games.PromotionGames', to='games.Games'),
        ),
    ]
