# Generated by Django 2.0.5 on 2018-08-01 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180731_1455'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PRG',
            new_name='PromotionGames',
        ),
        migrations.AddField(
            model_name='promotion',
            name='reward',
            field=models.ManyToManyField(through='games.PromotionGames', to='games.Games'),
        ),
        migrations.AlterField(
            model_name='session',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 1, 7, 49, 7, 427993, tzinfo=utc)),
        ),
    ]
